import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-research-grant-cost-transfer-compliance",
  "engine": "recovery",
  "title": "Research Grant Cost-Transfer Compliance",
  "shortTitle": "Research Grant Cost-Transfer Compliance",
  "tagline": "Prevent unsupported cost transfers and preserve reimbursable research expenditures through evidence, timing, and allocation controls.",
  "industry": "Sponsored Research Compliance",
  "buyer": "Universities and research institutions",
  "uiPort": 4695,
  "apiPort": 5695,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Research Grant Cost-Transfer Compliance converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports in one accountable workflow. Prevent unsupported cost transfers and preserve reimbursable research expenditures through evidence, timing, and allocation controls.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Research Grant Cost-Transfer Compliance evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("award-budget-registry","RGC01","Award budget registry","Execute award budget registry using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed award budget registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Award budget registry Reference","text","RGC01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("ledger-transaction-ingestion","RGC02","Ledger transaction ingestion","Execute ledger transaction ingestion using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed ledger transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Ledger transaction ingestion Reference","text","RGC02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("payroll-effort-linkage","RGC03","Payroll effort linkage","Execute payroll effort linkage using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed payroll effort linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Payroll effort linkage Reference","text","RGC03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("original-charge-validation","RGC04","Original charge validation","Execute original charge validation using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed original charge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Original charge validation Reference","text","RGC04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("transfer-reason-classification","RGC05","Transfer reason classification","Execute transfer reason classification using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed transfer reason classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Transfer reason classification Reference","text","RGC05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("allocability-assessment","RGC06","Allocability assessment","Execute allocability assessment using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed allocability assessment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Allocability assessment Reference","text","RGC06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("benefit-to-award-evidence","RGC07","Benefit-to-award evidence","Execute benefit-to-award evidence using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed benefit-to-award evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Benefit-to-award evidence Reference","text","RGC07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("ninety-day-deadline-control","RGC08","Ninety-day deadline control","Execute ninety-day deadline control using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed ninety-day deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Ninety-day deadline control Reference","text","RGC08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("cost-share-treatment","RGC09","Cost share treatment","Execute cost share treatment using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed cost share treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Cost share treatment Reference","text","RGC09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("pi-approval-workflow","RGC10","PI approval workflow","Execute pi approval workflow using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed pi approval workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","PI approval workflow Reference","text","RGC10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("high-risk-transfer-review","RGC11","High-risk transfer review","Execute high-risk transfer review using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed high-risk transfer review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","High-risk transfer review Reference","text","RGC11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("journal-entry-generation","RGC12","Journal entry generation","Execute journal entry generation using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed journal entry generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Journal entry generation Reference","text","RGC12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("sponsor-reporting-reconciliation","RGC13","Sponsor reporting reconciliation","Execute sponsor reporting reconciliation using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed sponsor reporting reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Sponsor reporting reconciliation Reference","text","RGC13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("audit-evidence-package","RGC14","Audit evidence package","Execute audit evidence package using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed audit evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Audit evidence package Reference","text","RGC14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]}),
feature("department-award-analytics","RGC15","Department award analytics","Execute department award analytics using award budgets, general-ledger transactions, payroll, effort, invoices, transfer requests, allocability evidence, approvals, deadlines, and sponsor reports.","Produce a governed department award analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Award / Cost Transfer","text","Award / Cost Transfer · Standard Case"],["caseReference","Department award analytics Reference","text","RGC15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1222500],["supportedAmount","Evidence-Supported Amount","currency",1026900],["domainDriver","Transfer Reason","select","Correction",["Correction","Late allocation","Cost share"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Award budget registry case","Ledger transaction ingestion case","Payroll effort linkage case","Original charge validation case","Transfer reason classification case"]})
]);
